// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzQ6jPc1UzxQpQeCN5OESNlA0zgoZkovc',
    appId: '1:169457956060:android:351b88ce70c076932d7019',
    messagingSenderId: '169457956060',
    projectId: 'dealping-2025',
    storageBucket: 'dealping-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpalU3E2yn1mG-0UqwRyVWqeoXzEKkZBI',
    appId: '1:169457956060:ios:2bb78421d72744222d7019',
    messagingSenderId: '169457956060',
    projectId: 'dealping-2025',
    storageBucket: 'dealping-2025.firebasestorage.app',
    iosClientId: '169457956060-0uqruapuddglo0c7k57nat19rat7qs1a.apps.googleusercontent.com',
    iosBundleId: 'com.naveen.dealping',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs70MkYHHi19ZfWT5etDRnX0WThfTuRGw',
    appId: '1:169457956060:web:483011ec70dbac262d7019',
    messagingSenderId: '169457956060',
    projectId: 'dealping-2025',
    authDomain: 'dealping-2025.firebaseapp.com',
    storageBucket: 'dealping-2025.firebasestorage.app',
    measurementId: 'G-M6WBKW2V8D',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpalU3E2yn1mG-0UqwRyVWqeoXzEKkZBI',
    appId: '1:169457956060:ios:02d0f41fa227372f2d7019',
    messagingSenderId: '169457956060',
    projectId: 'dealping-2025',
    storageBucket: 'dealping-2025.firebasestorage.app',
    iosClientId: '169457956060-idltmoqbvfcstjn2blrjhbv2rkhmkn6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.dealPing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs70MkYHHi19ZfWT5etDRnX0WThfTuRGw',
    appId: '1:169457956060:web:423e29c654eff62b2d7019',
    messagingSenderId: '169457956060',
    projectId: 'dealping-2025',
    authDomain: 'dealping-2025.firebaseapp.com',
    storageBucket: 'dealping-2025.firebasestorage.app',
    measurementId: 'G-3XCFYWR6JH',
  );

}